name: "Kafka KRaft"
description: "Creates a simple Kafka KRaft broker for integration testing"
author: "Spicy Parrot"
branding:
  icon: "alert-circle"
  color: "purple"
inputs:
  kafka-version:
    description: "Kafka version to use"
    default: "3.7.0"
    required: false
  kafka-topics:
    description: "A comma separated list of topics with their partition counts - e.g. foobar,10,test,5"
    default: ""
    required: false
  kafka-cache:
    description: "Whether to cache kafka archive"
    default: 'false'
    required: false

env:
  SCALA_VERSION: '2.13'

runs:
  using: "composite"
  steps:
    - name: 🏗 Checkout Kafka kraft repo
      uses: actions/checkout@v4
      with:
        repository: PawelKawula/kafka-kraft-action
        path: "kafka"


    - name: Restore cached kafka archive
      id: kafka-archive-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          /tmp/kafka_*.tgz
        key: kafka_${{ inputs.kafka-version }}

    - name: Download kafka archive if not cached
      shell: bash
      if: steps.kafka-archive-restore.outputs.cache-hit != 'true'
      run: wget -O /tmp/kafka_-${{ inputs.kafka-version }}.tgz https://archive.apache.org/dist/kafka/${{ inputs.kafka-version }}/kafka_${{ env.SCALA_VERSION }}-${{ inputs.kafka-version }}.tgz

    - name: Store cached kafka archive
      id: kafka-archive-save
      if: steps.kafka-archive-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          /tmp/kafka_*.tgz
        key: ${{ steps.kafka-archive-restore.outputs.cache-primary-key }}

    - name: 🧠 Bring up KRaft Broker
      working-directory: kafka
      shell: bash
      id: kafka
      run: ./scripts/start.sh --version ${{ inputs.kafka-version }}

    - name: 🪄 Create Kafka topics
      working-directory: kafka
      shell: bash
      run: ./scripts/create_topics.sh --topics ${{ inputs.kafka-topics }}
